"""Reusable Orbea automation services for the UltraBike desktop app."""

from .catalogue import (
    CatalogueEntry,
    CatalogueIndex,
    MatchResult,
    extract_template_codes,
    normalize_code,
    select_representative_variant,
)
from .checkpoint import (
    RunCheckpoint,
    create_run_directory,
    find_latest_compatible_run,
)
from .descriptions import (
    DescriptionProgress,
    DescriptionRunConfig,
    DescriptionRunResult,
    OrbeaDescriptionService,
    run_description_extraction,
)
from .models import (
    CancellationToken,
    FilterOption,
    OrbeaRunConfig,
    OrbeaRunResult,
    PimboFilterOptions,
    PimboFilterSpec,
    RunCancelled,
    RunProgress,
)
from .photos import (
    OrbeaPhotoBatchResult,
    OrbeaPhotoProduct,
    OrbeaPhotoProgress,
    OrbeaPhotoRunResult,
    OrbeaPhotoService,
    OrbeaPhotoVariant,
    download_orbea_photo_batches,
    download_orbea_photos,
    normalize_orbea_product_url,
    parse_orbea_photo_product,
    unique_orbea_product_urls,
)
from .service import OrbeaAutomationService, run_pipeline
from .table_images import (
    OrbeaTableBatchResult,
    OrbeaTableImageService,
    OrbeaTableProductResult,
    OrbeaTableProgress,
    normalize_orbea_table_url,
    unique_orbea_table_urls,
)

__all__ = [
    "CancellationToken",
    "CatalogueEntry",
    "CatalogueIndex",
    "DescriptionProgress",
    "DescriptionRunConfig",
    "DescriptionRunResult",
    "FilterOption",
    "MatchResult",
    "OrbeaAutomationService",
    "OrbeaDescriptionService",
    "OrbeaPhotoBatchResult",
    "OrbeaPhotoProduct",
    "OrbeaPhotoProgress",
    "OrbeaPhotoRunResult",
    "OrbeaPhotoService",
    "OrbeaPhotoVariant",
    "OrbeaRunConfig",
    "OrbeaRunResult",
    "OrbeaTableBatchResult",
    "OrbeaTableImageService",
    "OrbeaTableProductResult",
    "OrbeaTableProgress",
    "PimboFilterOptions",
    "PimboFilterSpec",
    "RunCancelled",
    "RunCheckpoint",
    "RunProgress",
    "create_run_directory",
    "extract_template_codes",
    "find_latest_compatible_run",
    "normalize_code",
    "normalize_orbea_table_url",
    "run_pipeline",
    "run_description_extraction",
    "download_orbea_photos",
    "download_orbea_photo_batches",
    "normalize_orbea_product_url",
    "parse_orbea_photo_product",
    "unique_orbea_product_urls",
    "unique_orbea_table_urls",
    "select_representative_variant",
]
